name: HeroLock
main: com.herocraftonline.rightlegred.herolock.HeroLock
version: 0.0.1
description: A system which allows users to password protect chests.
database: true
commands:
  lock:
    description: Lock a chest
    usage: /lock <password>
  unlock:
    description: Unlock a chest
    usage: /unlock <password>